# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=https://loja.com
smallrye.jwt.sign.key.location=privateKey.pem

# Kafka Dev Services
%dev.quarkus.kafka.devservices.enabled=true

# Kafka channels
mp.messaging.outgoing.estoque-baixo-out.connector=smallrye-kafka
mp.messaging.outgoing.estoque-baixo-out.topic=estoque-baixo
mp.messaging.outgoing.estoque-baixo-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.estoque-baixo-in.connector=smallrye-kafka
mp.messaging.incoming.estoque-baixo-in.topic=estoque-baixo
mp.messaging.incoming.estoque-baixo-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.estoque-baixo-in.auto.offset.reset=earliest

